

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    workflow_dispatch:

jobs:
  create folder:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: create folder  ON REMETO VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami
  build:

    runs-on: ubuntu-latest

    steps:
    - name: telechargement des code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -Dmaven.test.skip=true -B package --file pom.xml


