

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    workflow_dispatch:

jobs:
  create-folder:
    name: Crer un folders
    runs-on: ubuntu-latest
    steps:
      - name: create folder  ON REMETO VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: mkdir -p ~/opt/applications/sa
  build-project:
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
    - name: telechargement des code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -Dmaven.test.skip=true -B package --file pom.xml

    - name: Rename jar
      run: mv target/*.jar target/sa.jar
    - name: Copy file via ssh
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "target/sa.jar"
        target: "~/opt/applications/sa"
        strip_components: 1
  run-projetc:
    name: run projet
    runs-on: ubuntu-latest
    needs :  build-project
    steps:
      - name: run projet
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ln -sf ~/opt/applications/sa/sa.jar 
            /etc/init.d/sa start
