name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Téléchargement du code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true -B package --file pom.xml

      - name: Rename jar
        run: mv target/*.jar target/sa.jar

      - name: Copy file via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}   # ✅ clé privée SSH
          port: ${{ secrets.PORT }}
          source: "target/sa.jar,Dockerfile"
          target: "/opt/cicd"
          strip_components: 0

      - name: Deployer to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}   # ✅ clé privée SSH
          port: ${{ secrets.PORT }}
          script: |
            cd /opt/cicd
            docker build -t monapplication .
            docker stop monapplication || true
            docker rm monapplication || true
            docker run -d --name monapplication monapplication
            docker ps
